version: '3.4'
services:
  markr:
    build: .
    ports:
      - '4567:4567'
    environment:
      MYSQL_DATABASE: markr
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: password
    volumes:
      - './:/app'
    depends_on:
      - db
  db:
    image: mysql:8.0
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: markr
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
