version: '3.4'
services:
  markr:
    build: .
    ports:
      - '4567:4567'
    command: ["go", "run", "cmd/main.go", "cmd/logger.go"]
    environment:
      MYSQL_DATABASE: markr_db
      MYSQL_HOST_PORT: 3306
      MYSQL_HOST_URL: db
      USERNAME: root
      PASSWORD: password
    volumes:
      - './:/app'
    depends_on:
      - db
  db:
    image: mysql:8.0
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: markr_db
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
  tests:
    build: .
    command: ["go", "test", "./...", "-cover"]
